spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: event_sourcing_db
      auto-index-creation: true

logging:
  level:
    com.example: DEBUG
    org.springframework.data.mongodb: DEBUG
